# dev-values-passwordgenrator-v1.yaml
image:
  repository: anoopkrrish07/apiapp
  pullPolicy: IfNotPresent
  tag: "latest"

# imagePullSecrets: ## Only for docker hub or external image repos
#   - name: apiapp-secret

# replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# service:
#   type: ClusterIP
#   port: 5000

service:
  type: LoadBalancer
  port: 5000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
