apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-default
spec:
  amiFamily: AL2 # Amazon Linux 2
  instanceProfile: "<add the instance profile>"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<cluster name>" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<cluster name>" # replace with your cluster name
  tags:
    Name: karpenter.sh/pool/default
