name: Build and deploy on EKS

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # semantic version

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
env:
  AWS_DEFAULT_REGION: us-east-1
  EKS_CLUSTER_NAME: dev-eks-cluster
  NAMESPACE: dev-app
jobs:
  app_build:
    name: "Building Container Image"
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.DEV_AWS_ROLE_ARN }}
        role-session-name: appbuild
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Getting the tag value
      id: getting-tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push the tagged docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
        IMAGE_TAG: latest
      run: |
        cd api_app
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0

    - name: Deploy on EKS
      run: |
        cd kube_deploy/helm-charts/app-charts
        helm upgrade --install dev-passgen-$TAG_NAME ./api-app/app-passgen-api/ --create-namespace --namespace $NAMESPACE ./env_values/dev/app-passgen-api/dev-values-passgen-v1.yaml
